html_template: ".TEMPLATE"
# TODO: 431 needed
r_exe_path: "PATH/R/R-4.3.1/bin/Rscript.exe"
r_script_path: "PATH/DAPAR_analysis_v3.r"
r_rrvgo_path: "PATH/R Scripts/rrvgo_analyser_v2.r"
gh_token: GH_TOKEN

# Mapping of variables to columns for Spectronaut
Spectronaut:
  file_name_col: 'R.FileName'
  protein_group_col: 'PG.ProteinAccessions'
  protein_ids_col: 'PG.ProteinAccessions'
  genes_col: 'PG.Genes'
  precursor_id_col: 'EG.PrecursorId'
  precursor_quantity_col: 'PEP.Quantity'
  modified_sequence_col: 'EG.ModifiedSequence'
  protein_names_col: 'Protein.Names' # Probably not

# Mapping of variables to columns for DIANN
DIANN:
  file_name_col: 'File.Name'
  protein_group_col: 'Protein.Group'
  protein_ids_col: 'Protein.Ids'
  genes_col: 'Genes'
  precursor_id_col: 'Precursor.Id'
  precursor_quantity_col: 'Precursor.Quantity'
  modified_sequence_col: 'Modified.Sequence'
  protein_names_col: 'Protein.Names'

column_mapping:
  File.Name:
    new: R.FileName
    mapped: False
  Protein.Group:
    new: PG.ProteinAccessions
    mapped: False
  Genes:
    new: PG.Genes
    mapped: False
  Precursor.Id:
    new: EG.PrecursorId
    mapped: False
  Precursor.Quantity:
    new: PEP.Quantity
    mapped: False
  Modified.Sequence:
    new: EG.ModifiedSequence
    mapped: False

colour_palette:
  - '#D55E00'
  - '#56B4E9'
  - '#009E73'
  - '#F0E442'
  - '#0072B2'
  - '#E69F00'
  - '#CC79A7'
  - '#b825af'
  - '#57832e'
  - '#9620fc'
  - '#b2d27a'
  - '#622e86'
  - '#1cf1a3'
  - '#f6568b'
  - '#18857f'
  - '#ffb2be'
  - '#6e390d'
  - '#f27ff5'
  - '#c66d0e'
  - '#3147ed'

extra_condition_columns_defaults:
  Bait: "None"
  Marker: "None"
  POIs: "None"
